services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      - MONGO_URI=value
      - MONGO_USER=
      - MONGO_PASSWORD=
    env_file:
      - .
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node-server
    restart: always
    environment:
      - JWT=value
    env_file:
      - .
    ports:
      - "8080:8080"
    depends_on:
      - mongo

volumes:
  mongo_data: {}