
services:
  client:
    container_name: next_client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    env_file:
      - /client/.env
    networks:
      - app-network
  
  server:
    container_name: express_server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - /server/.env
    networks:
      - app-network
  
  redis:
    container_name: redis_cache
    image: "redis:latest"
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge