services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/movies
      - JWT_ACCESS=
      - JWT_REFRESH=
      - MAIL_USER=
      - MAIL_PASS=
      - TMDB_KEY=
    depends_on:
      - mongo
    networks:
      - mern-network

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - mern-network

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  mern-network:
    driver: bridge