services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/movies
      - JWT_ACCESS=jwt_access_token_secret
      - JWT_REFRESH=jwt_refresh_token_secret
      - MAIL_USER=abdusharipovizzat03@gmail.com
      - MAIL_PASS=olrjnjigzdquzomc
      - TMDB_KEY=72e0743d4c44f2e89be67102c4ed3fe5
    depends_on:
      - mongo
    networks:
      - mern-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mern-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  mern-network:
    driver: bridge