import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MovieProvider } from "./context/MovieProvider";
import { Toaster } from "react-hot-toast";
import { TvProvier } from "./interface/TvProvier";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Movie Time",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <MovieProvider>
           <TvProvier>
                {children}
                <Toaster position={'bottom-right'} reverseOrder={false} />
           </TvProvier>
       </MovieProvider>
      </body>
    </html>
  );
}
